# Generated by Django 2.0.1 on 2018-03-04 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180304_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lastm_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
