# Generated by Django 2.0.1 on 2018-03-04 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180304_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
