# Generated by Django 2.0.1 on 2018-03-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180304_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='lastm_date',
            field=models.DateField(),
        ),
    ]
