# Generated by Django 2.0.1 on 2018-03-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180304_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='lastm_date',
            field=models.DateField(auto_now=True),
        ),
    ]
