# Generated by Django 2.0.1 on 2018-03-04 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180304_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='lastm_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
